development:
  adapter: postgresql
  database: journaldb
  username: rubyuser
  password: rubypass
  host: localhost
  encoding: utf8

test:
  adapter: postgresql
  database: journaldb
  username: rubyuser
  password: rubypass
  host: localhost
  encoding: utf8

production:
  adapter: postgresql
  database: journaldb
  username: rubyuser
  password: rubypass
  host: localhost
  encoding: utf8